language: cpp

dist: bionic

git:
  depth: 1
  submodules: true

matrix:
  include:

# Coverage
    - name: Coverage (Linux - GCC 7 - Debug)
      arch: amd64
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - ninja-build
            - lcov
      env:
        - COMPILER=g++-7
        - CMAKE_EXTRA_ARGS="-DDYNAMICBITSET_ENABLE_COVERAGE=ON"
        - BUILD_TYPE=Debug
      after_success:
        - cd ${TRAVIS_BUILD_DIR}
        # Create lcov report
        # capture coverage info
        - lcov --directory . --capture --output-file coverage.info
        # keep only dynamic_bitset.h
        - lcov --extract coverage.info '*/dynamic_bitset.hpp' --output-file coverage.info
        # Uploading to CodeCov
        # '-f' specifies file(s) to use and disables manual coverage gathering and file search which has already been done above
        - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

# Linux
## GCC
### GCC 7
    - name: Linux - GCC 7 - Debug
      arch: amd64
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - ninja-build
      env:
        - COMPILER=g++-7
        - BUILD_TYPE=Debug

    - name: Linux - GCC 7 - Release
      arch: amd64
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - ninja-build
      env:
        - COMPILER=g++-7
        - BUILD_TYPE=Release

### GCC 8
    - name: Linux - GCC 8 - Debug
      arch: amd64
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - ninja-build
      env:
        - COMPILER=g++-8
        - BUILD_TYPE=Debug

    - name: Linux - GCC 8 - Release
      arch: amd64
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - ninja-build
      env:
        - COMPILER=g++-8
        - BUILD_TYPE=Release

### GCC 9
    - name: Linux - GCC 9 - Debug
      arch: amd64
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - ninja-build
      env:
        - COMPILER=g++-9
        - BUILD_TYPE=Debug

    - name: Linux - GCC 9 - Release
      arch: amd64
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - ninja-build
      env:
        - COMPILER=g++-9
        - BUILD_TYPE=Release

### GCC 10
    - name: Linux - GCC 10 - Debug
      arch: amd64
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
            - ninja-build
      env:
        - COMPILER=g++-10
        - BUILD_TYPE=Debug

    - name: Linux - GCC 10 - Release
      arch: amd64
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
            - ninja-build
      env:
        - COMPILER=g++-10
        - BUILD_TYPE=Release

## Clang
### Clang 5
    - name: Linux - Clang 5 - Debug
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-5.0
          packages:
            - clang-5.0
            - g++-7
            - ninja-build
      env:
        - COMPILER=clang++-5.0
        - BUILD_TYPE=Debug

    - name: Linux - Clang 5 - Release
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-5.0
          packages:
            - clang-5.0
            - g++-7
            - ninja-build
      env:
        - COMPILER=clang++-5.0
        - BUILD_TYPE=Release

### Clang 6
    - name: Linux - Clang 6 - Debug
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-6.0
          packages:
            - clang-6.0
            - g++-7
            - ninja-build
      env:
        - COMPILER=clang++-6.0
        - BUILD_TYPE=Debug

    - name: Linux - Clang 6 - Release
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-6.0
          packages:
            - clang-6.0
            - g++-7
            - ninja-build
      env:
        - COMPILER=clang++-6.0
        - BUILD_TYPE=Release

### Clang 7
    - name: Linux - Clang 7 - Debug
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-7
          packages:
            - clang-7
            - g++-7
            - ninja-build
      env:
        - COMPILER=clang++-7
        - BUILD_TYPE=Debug

    - name: Linux - Clang 7 - Release
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-7
          packages:
            - clang-7
            - g++-7
            - ninja-build
      env:
        - COMPILER=clang++-7
        - BUILD_TYPE=Release

### Clang 8
    - name: Linux - Clang 8 - Debug
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-8
          packages:
            - clang-8
            - g++-8
            - ninja-build
      env:
        - COMPILER=clang++-8
        - BUILD_TYPE=Debug

    - name: Linux - Clang 8 - Release
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-8
          packages:
            - clang-8
            - g++-8
            - ninja-build
      env:
        - COMPILER=clang++-8
        - BUILD_TYPE=Release

### Clang 9
    - name: Linux - Clang 9 - Debug
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-9
          packages:
            - clang-9
            - g++-9
            - ninja-build
      env:
        - COMPILER=clang++-9
        - BUILD_TYPE=Debug

    - name: Linux - Clang 9 - Release
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-9
          packages:
            - clang-9
            - g++-9
            - ninja-build
      env:
        - COMPILER=clang++-9
        - BUILD_TYPE=Release

### Clang 10
    - name: Linux - Clang 10 - Debug
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-10
          packages:
            - clang-10
            - g++-10
            - ninja-build
      env:
        - COMPILER=clang++-10
        - BUILD_TYPE=Debug

    - name: Linux - Clang 10 - Release
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-10
          packages:
            - clang-10
            - g++-10
            - ninja-build
      env:
        - COMPILER=clang++-10
        - BUILD_TYPE=Release

# OSX
## Xcode
### Xcode 10.2
    - name: OSX - Xcode 10.2 - Debug
      arch: amd64
      os: osx
      osx_image: xcode10.2
      env:
        - BUILD_TYPE=Debug

    - name: OSX - Xcode 10.2 - Release
      arch: amd64
      os: osx
      osx_image: xcode10.2
      env:
        - BUILD_TYPE=Release

### Xcode 10.3
    - name: OSX - Xcode 10.3 - Debug
      arch: amd64
      os: osx
      osx_image: xcode10.3
      env:
        - BUILD_TYPE=Debug

    - name: OSX - Xcode 10.3 - Release
      arch: amd64
      os: osx
      osx_image: xcode10.3
      env:
        - BUILD_TYPE=Release

### Xcode 11
    - name: OSX - Xcode 11 - Debug
      arch: amd64
      os: osx
      osx_image: xcode11
      env:
        - BUILD_TYPE=Debug

    - name: OSX - Xcode 11 - Release
      arch: amd64
      os: osx
      osx_image: xcode11
      env:
        - BUILD_TYPE=Release

### Xcode 11.1
    - name: OSX - Xcode 11.1 - Debug
      arch: amd64
      os: osx
      osx_image: xcode11.1
      env:
        - BUILD_TYPE=Debug

    - name: OSX - Xcode 11.1 - Release
      arch: amd64
      os: osx
      osx_image: xcode11.1
      env:
        - BUILD_TYPE=Release

### Xcode 11.2
    - name: OSX - Xcode 11.2 - Debug
      arch: amd64
      os: osx
      osx_image: xcode11.2
      env:
        - BUILD_TYPE=Debug

    - name: OSX - Xcode 11.2 - Release
      arch: amd64
      os: osx
      osx_image: xcode11.2
      env:
        - BUILD_TYPE=Release

### Xcode 11.3
    - name: OSX - Xcode 11.3 - Debug
      arch: amd64
      os: osx
      osx_image: xcode11.3
      env:
        - BUILD_TYPE=Debug

    - name: OSX - Xcode 11.3 - Release
      arch: amd64
      os: osx
      osx_image: xcode11.3
      env:
        - BUILD_TYPE=Release

### Xcode 11.4
    - name: OSX - Xcode 11.4 - Debug
      arch: amd64
      os: osx
      osx_image: xcode11.4
      env:
        - BUILD_TYPE=Debug

    - name: OSX - Xcode 11.4 - Release
      arch: amd64
      os: osx
      osx_image: xcode11.4
      env:
        - BUILD_TYPE=Release

### Xcode 11.5
    - name: OSX - Xcode 11.5 - Debug
      arch: amd64
      os: osx
      osx_image: xcode11.5
      env:
        - BUILD_TYPE=Debug

    - name: OSX - Xcode 11.5 - Release
      arch: amd64
      os: osx
      osx_image: xcode11.5
      env:
        - BUILD_TYPE=Release

### Xcode 11.6
    - name: OSX - Xcode 11.6 - Debug
      arch: amd64
      os: osx
      osx_image: xcode11.6
      env:
        - BUILD_TYPE=Debug

    - name: OSX - Xcode 11.6 - Release
      arch: amd64
      os: osx
      osx_image: xcode11.6
      env:
        - BUILD_TYPE=Release

### Xcode 12
    - name: OSX - Xcode 12 - Debug
      arch: amd64
      os: osx
      osx_image: xcode12
      env:
        - BUILD_TYPE=Debug

    - name: OSX - Xcode 12 - Release
      arch: amd64
      os: osx
      osx_image: xcode12
      env:
        - BUILD_TYPE=Release

script:
  - |
     if [[ (-x $(which brew)) ]]; then
       brew update
       brew install cmake ninja
       brew upgrade cmake ninja
     fi
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - if [[ "${BUILD_TYPE}" == "" ]]; then export BUILD_TYPE=Debug; fi

  - uname -a
  - cmake --version
  - ninja --version
  - ${CXX} --version

  - mkdir cmake-build
  - cd cmake-build
  - cmake .. -DCMAKE_CONFIGURATION_TYPES=${BUILD_TYPE} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DDYNAMICBITSET_BUILD_DOCS=OFF ${CMAKE_EXTRA_ARGS} -GNinja
  - cmake --build . --config ${BUILD_TYPE}
  - ctest --output-on-failure
